In [1]:
import time
import pandas as pd
from nba_api.stats.static import teams
from nba_api.stats.endpoints import commonteamroster, playercareerstats

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
#models.Base.metadata.create_all(bind=engine)
#db = sessionDB()

In [4]:
all_teams = teams.get_teams()
all_teams

[{'id': 1610612737,
  'full_name': 'Atlanta Hawks',
  'abbreviation': 'ATL',
  'nickname': 'Hawks',
  'city': 'Atlanta',
  'state': 'Georgia',
  'year_founded': 1949},
 {'id': 1610612738,
  'full_name': 'Boston Celtics',
  'abbreviation': 'BOS',
  'nickname': 'Celtics',
  'city': 'Boston',
  'state': 'Massachusetts',
  'year_founded': 1946},
 {'id': 1610612739,
  'full_name': 'Cleveland Cavaliers',
  'abbreviation': 'CLE',
  'nickname': 'Cavaliers',
  'city': 'Cleveland',
  'state': 'Ohio',
  'year_founded': 1970},
 {'id': 1610612740,
  'full_name': 'New Orleans Pelicans',
  'abbreviation': 'NOP',
  'nickname': 'Pelicans',
  'city': 'New Orleans',
  'state': 'Louisiana',
  'year_founded': 2002},
 {'id': 1610612741,
  'full_name': 'Chicago Bulls',
  'abbreviation': 'CHI',
  'nickname': 'Bulls',
  'city': 'Chicago',
  'state': 'Illinois',
  'year_founded': 1966},
 {'id': 1610612742,
  'full_name': 'Dallas Mavericks',
  'abbreviation': 'DAL',
  'nickname': 'Mavericks',
  'city': 'Dallas',
  'state': 'Texas',
  'year_founded': 1980},
 {'id': 1610612743,
  'full_name': 'Denver Nuggets',
  'abbreviation': 'DEN',
  'nickname': 'Nuggets',
  'city': 'Denver',
  'state': 'Colorado',
  'year_founded': 1976},
 {'id': 1610612744,
  'full_name': 'Golden State Warriors',
  'abbreviation': 'GSW',
  'nickname': 'Warriors',
  'city': 'San Francisco',
  'state': 'California',
  'year_founded': 1946},
 {'id': 1610612745,
  'full_name': 'Houston Rockets',
  'abbreviation': 'HOU',
  'nickname': 'Rockets',
  'city': 'Houston',
  'state': 'Texas',
  'year_founded': 1967},
 {'id': 1610612746,
  'full_name': 'Los Angeles Clippers',
  'abbreviation': 'LAC',
  'nickname': 'Clippers',
  'city': 'Los Angeles',
  'state': 'California',
  'year_founded': 1970},
 {'id': 1610612747,
  'full_name': 'Los Angeles Lakers',
  'abbreviation': 'LAL',
  'nickname': 'Lakers',
  'city': 'Los Angeles',
  'state': 'California',
  'year_founded': 1948},
 {'id': 1610612748,
  'full_name': 'Miami Heat',
  'abbreviation': 'MIA',
  'nickname': 'Heat',
  'city': 'Miami',
  'state': 'Florida',
  'year_founded': 1988},
 {'id': 1610612749,
  'full_name': 'Milwaukee Bucks',
  'abbreviation': 'MIL',
  'nickname': 'Bucks',
  'city': 'Milwaukee',
  'state': 'Wisconsin',
  'year_founded': 1968},
 {'id': 1610612750,
  'full_name': 'Minnesota Timberwolves',
  'abbreviation': 'MIN',
  'nickname': 'Timberwolves',
  'city': 'Minnesota',
  'state': 'Minnesota',
  'year_founded': 1989},
 {'id': 1610612751,
  'full_name': 'Brooklyn Nets',
  'abbreviation': 'BKN',
  'nickname': 'Nets',
  'city': 'Brooklyn',
  'state': 'New York',
  'year_founded': 1976},
 {'id': 1610612752,
  'full_name': 'New York Knicks',
  'abbreviation': 'NYK',
  'nickname': 'Knicks',
  'city': 'New York',
  'state': 'New York',
  'year_founded': 1946},
 {'id': 1610612753,
  'full_name': 'Orlando Magic',
  'abbreviation': 'ORL',
  'nickname': 'Magic',
  'city': 'Orlando',
  'state': 'Florida',
  'year_founded': 1989},
 {'id': 1610612754,
  'full_name': 'Indiana Pacers',
  'abbreviation': 'IND',
  'nickname': 'Pacers',
  'city': 'Indiana',
  'state': 'Indiana',
  'year_founded': 1976},
 {'id': 1610612755,
  'full_name': 'Philadelphia 76ers',
  'abbreviation': 'PHI',
  'nickname': '76ers',
  'city': 'Philadelphia',
  'state': 'Pennsylvania',
  'year_founded': 1949},
 {'id': 1610612756,
  'full_name': 'Phoenix Suns',
  'abbreviation': 'PHX',
  'nickname': 'Suns',
  'city': 'Phoenix',
  'state': 'Arizona',
  'year_founded': 1968},
 {'id': 1610612757,
  'full_name': 'Portland Trail Blazers',
  'abbreviation': 'POR',
  'nickname': 'Trail Blazers',
  'city': 'Portland',
  'state': 'Oregon',
  'year_founded': 1970},
 {'id': 1610612758,
  'full_name': 'Sacramento Kings',
  'abbreviation': 'SAC',
  'nickname': 'Kings',
  'city': 'Sacramento',
  'state': 'California',
  'year_founded': 1948},
 {'id': 1610612759,
  'full_name': 'San Antonio Spurs',
  'abbreviation': 'SAS',
  'nickname': 'Spurs',
  'city': 'San Antonio',
  'state': 'Texas',
  'year_founded': 1976},
 {'id': 1610612760,
  'full_name': 'Oklahoma City Thunder',
  'abbreviation': 'OKC',
  'nickname': 'Thunder',
  'city': 'Oklahoma City',
  'state': 'Oklahoma',
  'year_founded': 1967},
 {'id': 1610612761,
  'full_name': 'Toronto Raptors',
  'abbreviation': 'TOR',
  'nickname': 'Raptors',
  'city': 'Toronto',
  'state': 'Ontario',
  'year_founded': 1995},
 {'id': 1610612762,
  'full_name': 'Utah Jazz',
  'abbreviation': 'UTA',
  'nickname': 'Jazz',
  'city': 'Utah',
  'state': 'Utah',
  'year_founded': 1974},
 {'id': 1610612763,
  'full_name': 'Memphis Grizzlies',
  'abbreviation': 'MEM',
  'nickname': 'Grizzlies',
  'city': 'Memphis',
  'state': 'Tennessee',
  'year_founded': 1995},
 {'id': 1610612764,
  'full_name': 'Washington Wizards',
  'abbreviation': 'WAS',
  'nickname': 'Wizards',
  'city': 'Washington',
  'state': 'District of Columbia',
  'year_founded': 1961},
 {'id': 1610612765,
  'full_name': 'Detroit Pistons',
  'abbreviation': 'DET',
  'nickname': 'Pistons',
  'city': 'Detroit',
  'state': 'Michigan',
  'year_founded': 1948},
 {'id': 1610612766,
  'full_name': 'Charlotte Hornets',
  'abbreviation': 'CHA',
  'nickname': 'Hornets',
  'city': 'Charlotte',
  'state': 'North Carolina',
  'year_founded': 1988}]

In [5]:
season = "2025-26"

In [6]:
team_list = [{team["abbreviation"]: team["id"]} for team in all_teams]
team_list

[{'ATL': 1610612737},
 {'BOS': 1610612738},
 {'CLE': 1610612739},
 {'NOP': 1610612740},
 {'CHI': 1610612741},
 {'DAL': 1610612742},
 {'DEN': 1610612743},
 {'GSW': 1610612744},
 {'HOU': 1610612745},
 {'LAC': 1610612746},
 {'LAL': 1610612747},
 {'MIA': 1610612748},
 {'MIL': 1610612749},
 {'MIN': 1610612750},
 {'BKN': 1610612751},
 {'NYK': 1610612752},
 {'ORL': 1610612753},
 {'IND': 1610612754},
 {'PHI': 1610612755},
 {'PHX': 1610612756},
 {'POR': 1610612757},
 {'SAC': 1610612758},
 {'SAS': 1610612759},
 {'OKC': 1610612760},
 {'TOR': 1610612761},
 {'UTA': 1610612762},
 {'MEM': 1610612763},
 {'WAS': 1610612764},
 {'DET': 1610612765},
 {'CHA': 1610612766}]

In [9]:
roster = commonteamroster.CommonTeamRoster(
    team_id=1610612737,
    league_id_nullable="00",
    season="2025-26"
)

roster_df = roster.get_data_frames()[0]
roster_df

,TeamID,SEASON,LeagueID,PLAYER,NICKNAME,PLAYER_SLUG,NUM,POSITION,HEIGHT,WEIGHT,BIRTH_DATE,AGE,EXP,SCHOOL,PLAYER_ID,HOW_ACQUIRED
0,1610612737,2025,00,Keshon Gilbert,Keshon,keshon-gilbert,NaN,G,6-4,200,"JUN 30, 2003",22.0,R,Iowa State,1642933,Signed on 03/04/26
1,1610612737,2025,00,RayJ Dennis,RayJ,rayj-dennis,00,G,6-1,180,"MAR 30, 2001",25.0,1,Baylor,1642484,Signed on 12/31/25
2,1610612737,2025,00,Jonathan Kuminga,Jonathan,jonathan-kuminga,0,F,6-7,225,"OCT 06, 2002",23.0,4,NBA G League Ignite,1630228,Traded from GSW on 02/05/26
3,1610612737,2025,00,Jalen Johnson,Jalen,jalen-johnson,1,F,6-8,219,"DEC 18, 2001",24.0,4,Duke,1630552,#20 Pick in 2021 Draft
4,1610612737,2025,00,Keaton Wallace,Keaton,keaton-wallace,2,G,6-3,185,"FEB 26, 1999",27.0,1,Texas-San Antonio,1630811,Signed on 09/29/23
5,1610612737,2025,00,CJ McCollum,CJ,cj-mccollum,3,G,6-3,190,"SEP 19, 1991",34.0,12,Lehigh,203468,Traded from WAS on 01/09/26
6,1610612737,2025,00,Gabe Vincent,Gabe,gabe-vincent,4,G,6-2,200,"JUN 14, 1996",29.0,6,California-Santa Barbara,1629216,Traded from LAL on 02/05/26
7,1610612737,2025,00,Dyson Daniels,Dyson,dyson-daniels,5,G,6-7,199,"MAR 17, 2003",23.0,3,NBA G League Ignite,1630700,Traded from NOP on 07/06/24
8,1610612737,2025,00,Nickeil Alexander-Walker,Nickeil,nickeil-alexander-walker,7,G,6-5,205,"SEP 02, 1998",27.0,6,Virginia Tech,1629638,Traded from MIN on 07/06/25
9,1610612737,2025,00,Buddy Hield,Buddy,buddy-hield,8,G,6-4,220,"DEC 17, 1992",33.0,9,Oklahoma,1627741,Traded from GSW on 02/05/26
10,1610612737,2025,00,Zaccharie Risacher,Zaccharie,zaccharie-risacher,10,F,6-8,200,"APR 08, 2005",21.0,1,JL Bourg-en-Bresse,1642258,#1 Pick in 2024 Draft
11,1610612737,2025,00,Christian Koloko,Christian,christian-koloko,10,C,6-11,225,"JUN 20, 2000",25.0,3,Arizona,1631132,Signed on 01/16/26
12,1610612737,2025,00,Tony Bradley,Tony,tony-bradley,13,C-F,6-10,248,"JAN 08, 1998",28.0,7,North Carolina,1628396,Signed on 04/06/26
13,1610612737,2025,00,Asa Newell,Asa,asa-newell,14,F,6-10,220,"OCT 05, 2005",20.0,R,Georgia,1642854,Draft Rights Traded from NOP on 06/25/25
14,1610612737,2025,00,Onyeka Okongwu,Onyeka,onyeka-okongwu,17,F-C,6-10,240,"DEC 11, 2000",25.0,5,Southern California,1630168,#6 Pick in 2020 Draft
15,1610612737,2025,00,Mouhamed Gueye,Mouhamed,mouhamed-gueye,18,F,6-11,210,"NOV 09, 2002",23.0,2,Washington State,1631243,Draft Rights Traded from BOS on 06/28/23
16,1610612737,2025,00,Corey Kispert,Corey,corey-kispert,24,F,6-6,224,"MAR 03, 1999",27.0,4,Gonzaga,1630557,Traded from WAS on 01/09/26
17,1610612737,2025,00,Jock Landale,Jock,jock-landale,31,C,6-11,255,"OCT 25, 1995",30.0,4,St. Mary's,1629111,Traded from UTA on 02/05/26

In [8]:
#using a loop cus if we do .apply() we have too many api calls and it times out (sad)

pid = 2544 #dont hardcode in prod
stats = playercareerstats.PlayerCareerStats(player_id=pid)
stats_df = stats.get_data_frames()[0]
#stats_df
current_stats = stats_df[stats_df["SEASON_ID"] == season]
points = current_stats["PTS"].iloc[0]
current_stats

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
22,2544,2025-26,00,1610612747,LAL,41.0,60,60,1989,473,919,0.515,77,243,0.317,233,316,0.737,43,321,364,432,72,35,179,81,1256